### PR TITLE
Ciara dev to dev

### LINKED ISSUE #10: Create Welcome Screen

### LINKED ISSUE #17: Create Teacher component
Create Teacher component

### LINKED ISSUE #22: Create form component

### LINKED ISSUE #23: Add Angular Material API

### PR DESCRIPTION
**Pull request by ciarapowell**
I added:
Angular Material, 
Student, Teacher, Survey components, 
Basic angular welcome page
Edited module referances

Would like to make more progress on welcome and routing between survey and welcome. 

resolves #17
resolves #22
resolves #10
resolves #23

### CODE REVIEW

**Comment by ltcarbonell** [comment]
Do you mind added the ticket numbers that this is for? Just so I can make sure I know what I'm looking at to review it.  The code itself looks good.  Just want to make sure that the logic is what I am thinking it is

**Comment by ciarapowell** [comment]
Sure no problem. I was not doing the full implementation of the issues I was creating and didn't want to fully close the issue. I would like to make subtasks but don't know where they are created.

**Comment by ltcarbonell** [comment]
Yeah they really isn't a really easy way to make sub-tasks.  What you can do is update the names so have the same heading for each subtask.  So something like:
`[Task Name] Sub Task 1`
`[Task Name] Sub Task 2`
`[Task Name] Sub Task 3`

**Comment by ciarapowell** [comment]
Create Teacher component #17
Create form component #22
Create Welcome Screen #10
Add Angular Material API #23

I will move these items to in code review when I get home.

**Comment by ltcarbonell** [comment]
Can you resolve these conflicts? Please and thank you!

**Comment by ltcarbonell** [comment]
resolves #17
resolves #22
resolves #10
resolves #23

**Comment by ltcarbonell** [comment]
Merging

**Pull request merged**
